CREATE DATABASE Optus;
GO

USE Optus;
GO

CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(20)NOT NULL,
Permissao VARCHAR(30)NOT NULL,
Senha VARCHAR(20)NOT NULL,
Email VARCHAR(20)NOT NULL,
);
GO

CREATE TABLE Estilo(
IdEstilo INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(20)
);
GO

CREATE TABLE Artistas(
IdArtista INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(20) NOT NULL,
IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo) 

);
GO

CREATE TABLE Album(
IdAlbum INT PRIMARY KEY IDENTITY NOT NULL,
DataDeLancamento DATE NOT NULL,
Localizacao VARCHAR(50) NOT NULL,
QtdMinutos DECIMAL NOT NULL,
Ativo VARCHAR(10) NOT NULL,
IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) 
);
GO

CREATE TABLE EstiloAlbum(
IdEstiloAlbum INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(20) NOT NULL,
IdEstilo INT FOREIGN KEY REFERENCES Estilo(IdEstilo),
IdAlbum INT FOREIGN KEY REFERENCES Album(IdAlbum) 
);
GO
